settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-rest-sample
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - database
    - readme.me
